config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Defines the root path route ("/")
  authenticate :user do
    root to: "documents#index", as: :authenticated_root
  end
  unauthenticated do
    root to: "home#index", as: :unauthenticated_root
  end

  resources :documents, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  
  has_one_attached :file
  has_one :report, dependent: :destroy
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :document
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :documents, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    documents_path
  end

  def render_turbo_flash
    turbo_stream.update("flash", partial: "shared/flashes")
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:query].present?
      query_params = "%#{params[:query]}%"
  
      @documents = current_user.documents
                     .joins(:report)
                     .joins("INNER JOIN active_storage_attachments ON active_storage_attachments.record_id = documents.id AND active_storage_attachments.record_type = 'Document'")
                     .joins("INNER JOIN active_storage_blobs ON active_storage_blobs.id = active_storage_attachments.blob_id")
                     .where(
                       "active_storage_blobs.filename ILIKE :query OR reports.data::jsonb->'tax_document'->>'nNF' ILIKE :query",
                       query: query_params
                     )
    else
      @documents = current_user.documents
    end
  end
  
  def show
    @document = Document.find(params[:id])
    
    if@document.report
      @report = JSON.parse(@document.report.data)
    else
      flash[:alert] = "Relatório ainda não disponível."
      redirect_to documents_path
    end
  end

  def new
    @document = Document.new
  end
  
  def create
    @document = current_user.documents.build(document_params)
    
    if @document.save
      #xml_content = @document.file.download
      doc = Document.find(@document.id)
      
      ProcessXmlJob.perform_later(@document.id, doc.file.download)
      
      flash[:success] = "Documento enviado com sucesso. Processando o arquivo..."
      redirect_to document_path(@document)
    else
      flash[:error] = "Erro ao enviar o documento."
      render :new, status::unprocessable_entity
    end
  end
  
  def search
  if params[:query].present?
    @documents = current_user.documents.joins(:report).where(
      "reports.data->'tax_document'->>'nNF' ILIKE :query OR reports.data->'tax_document'->>'emit' ILIKE :query OR reports.data->'tax_document'->>'dest' ILIKE :query",
      query: "%#{params[:query]}%"
    )
  else
    flash[:alert] = "Digite algo para pesquisar."
    redirect_to documents_path
  end
  end

  private

  def document_params
    params.require(:document).permit(:file)
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tailwind_classes_for(flash_type)
      {
        success: "bg-green-400 border-l-4 border-green-700 text-white",
        notice: "bg-blue-400 border-l-4 border-blue-700 text-white",
        error:   "bg-red-400 border-l-4 border-red-700 text-white",
        alert:   "bg-red-400 border-l-4 border-red-700 text-white"
      }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end 
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/documents/index.html.erb
<section class="py-8 bg-blueGray-50">
  <div class="container px-4 mx-auto flex justify-center">
    <div class="p-7 pb-16 pt-12 border border-dark-blue rounded-3xl w-11/12">
      <div class="flex flex-wrap px-9 md:mb-4 mb-4">
        <div class="w-full md:w-1/2">
          <h2 class="text-3xl font-heading font-sourcesans font-medium text-gray-500">
            Documentos
          </h2>
          <%= form_with url: documents_path, method: :get, class: "mt-4" do %>
            <div class="flex items">
              <%= text_field_tag :query, params[:query], class: "w-full border border-gray-300 rounded-lg p-2", placeholder: "Buscar pelo NF "  %>
              <%= submit_tag "Buscar", class: "bg-blue-500 text-white p-2 rounded-lg hover:bg-blue-600 transition duration-300" %>
            </div>
            <div class="mt-4">
              <%= link_to "Limpar Filtros", documents_path, class: "text-blue-600 hover:underline" %>
            </div>
          <% end %>
          <div class="overflow-x-auto my-6">
            <div class="inline-block min-w-full overflow-hidden">
              <% if @documents.any? %>
                <ul>
                  <% @documents.each do |document| %>
                    <li>
                      <%= link_to "Ver Relatório: #{document.file.filename}", document_path(document), class: "text-blue-600 hover:underline" %>
                    </li>
                  <% end %>
                </ul>
              <% else %>
                <p>Nenhum documento encontrado.</p>
              <% end %>
            </div>
          </div>
        </div>

        <div class="w-full md:w-1/2 max-w-max md:ml-auto">
          <%= link_to "Novo Documento", new_document_path, class: "inline-block bg-blue-500 text-white p-2 rounded-lg hover:bg-blue-600 transition duration-300" %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/documents/new.html.erb
<section class="py-8 bg-blueGray-50">
  <div class="container px-4 mx-auto flex justify-center">
    <div class="p-7 pb-16 pt-12 border border-dark-blue rounded-3xl w-11/12">
      <div class="flex flex-wrap px-9 mb-8 md:mb-0">
        <div class="w-full md:w-1/2">
          <h2 class="text-3xl font-heading font-sourcesans font-medium text-gray-500">
            Novo Documento
          </h2>
        </div>
        <div class="w-full md:w-1/2 max-w-max md:ml-auto">
          <%= link_to "Voltar para documentos", documents_path, class: "mt-4 inline-block bg-blue-500 text-white p-2 rounded-lg hover:bg-blue-600 transition duration-300" %>
        </div>
      </div>
      
      <div class="flex flex-wrap px-9 mt-8">
        <div class="w-full md:w-2/3 mx-auto">
          <%= form_with model: @document, local: true do |form| %>
            <div class="mb-4">
              <%= form.label :file, class: "block text-gray-700 text-sm font-bold mb-2" %>
              <%= form.file_field :file, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
            </div>
            <div>
              <%= form.submit "Upload", class: "w-full bg-blue-500 text-white p-2 rounded-lg hover:bg-blue-600 transition duration-300" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/documents/show.html.erb
<section class="py-8 bg-blueGray-50">
  <div class="container px-4 mx-auto flex justify-center">
    <div class="p-7 pb-16 pt-12 border border-dark-blue rounded-3xl w-11/12">
      <div class="flex items-center justify-between mb-6">
        <h1 class="text-3xl font-heading font-medium text-gray-500">
          Relatório para Documento <%= @document.id %>
        </h1>
        <%= link_to "Voltar para documentos", documents_path, class: "inline-block bg-blue-500 text-white p-2 rounded-lg hover:bg-blue-600 transition duration-300" %>
      </div>

      <div>
        <% if @report.present? %>
          <div class="mb-8">
            <h2 class="text-xl font-heading font-medium text-gray-600 mb-2">Dados do Documento Fiscal</h2>
            <p class="mb-2"><strong>Série:</strong> <%= @report["tax_document"]["serie"] %></p>
            <p class="mb-2"><strong>NF:</strong> <%= @report["tax_document"]["nNF"] %></p>
            <p class="mb-2"><strong>Data de Emissão:</strong> <%= @report["tax_document"]["dhEmi"] %></p>
            <p class="mb-2"><strong>Emitente:</strong> <%= @report["tax_document"]["emit"] %></p>
            <p class="mb-2"><strong>Destinatário:</strong> <%= @report["tax_document"]["dest"] %></p>
          </div>

          <div class="mb-8">
            <h2 class="text-xl font-heading font-medium text-gray-600 mb-2">Produtos</h2>
            <ul class="list-disc pl-5">
              <% @report["products"].each do |product| %>
                <li class="mb-2">
                  <strong>Nome:</strong> <%= product["name"] %>, 
                  <strong>NCM:</strong> <%= product["ncm"] %>, 
                  <strong>CFOP:</strong> <%= product["cfop"] %>, 
                  <strong>Unidade:</strong> <%= product["ucom"] %>, 
                  <strong>Quantidade:</strong> <%= product["qcom"] %>, 
                  <strong>Preço Unitário:</strong> <%= product["vuncom"] %>
                </li>
              <% end %>
            </ul>
          </div>

          <div class="mb-8">
            <h2 class="text-xl font-heading font-medium text-gray-600 mb-2">Impostos</h2>
            <p class="mb-2"><strong>ICMS:</strong> <%= @report["taxes"]["icms"] %></p>
            <p class="mb-2"><strong>IPI:</strong> <%= @report["taxes"]["ipi"] %></p>
            <p class="mb-2"><strong>PIS:</strong> <%= @report["taxes"]["pis"] %></p>
            <p class="mb-2"><strong>COFINS:</strong> <%= @report["taxes"]["cofins"] %></p>
          </div>

          <div class="mb-8">
            <h2 class="text-xl font-heading font-medium text-gray-600 mb-2">Totalizadores</h2>
            <p class="mb-2"><strong>Valor Total dos Produtos:</strong> <%= @report["totalizers"]["total_prod_value"] %></p>
            <p class="mb-2"><strong>Valor Total dos Impostos:</strong> <%= @report["totalizers"]["total_tax_value"] %></p>
          </div>
        <% else %>
          <p>Relatório ainda não disponível.</p>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer class="relative  pt-8 pb-6 mt-1">
  <div class="container mx-auto px-4">
    <div class="flex flex-wrap items-center md:justify-between justify-center">
      <div class="w-full md:w-6/12 px-4 mx-auto text-center">
        <div class="text-sm text-blueGray-500 font-semibold py-1">
        © 2024 Desenvolvido por <a href="https://www.linkedin.com/in/marcelo-silva-5273761bb/" target=_blank class="text-blueGray-500 hover:text-blueGray-800">Marcelo Candido</a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XmlProcessorApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div id="flash">
      <%= render 'shared/flashes' %>
    </div>

    <div>
      <%= render 'shared/navbar' %>
    </div>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if flash.any? %>
  <% flash.each do |type, message| %>
    <div class="fixed inset-x-0 top-20 flex items-end justify-right px-4 py-6 sm:p-6 justify-end z-30 pointer-events-none">
      <div data-controller="alert" class="max-w-sm w-full shadow-lg rounded px-4 py-3 rounded relative border-l-4 text-white pointer-events-auto alert <%= tailwind_classes_for(type) %>" data-alert-dismiss-after-value=3000 >
        <div class="p-2">
          <div class="flex items-start">
            <div class="ml-2 flex-1 pt-0.5">
              <p class="text-sm leading-5 font-medium">
              <%= message %>
              </p>
            </div>
            <div class="ml-4 flex-shrink-0 flex">
              <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>


  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="antialiased bg-gray-200 dark-mode:bg-gray-900">
  <div class="w-full text-gray-700 bg-dark dark-mode:text-gray-200 dark-mode:bg-gray-800">
    <div class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8 z-50">
      <div class="flex flex-row items-center justify-between p-4">
          <%= link_to (user_signed_in? ? authenticated_root_path : unauthenticated_root_path), class: "text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline" do %>
            processor_app
          <% end %>
      </div>
      <nav class="flex-col flex-grow hidden pb-4 md:pb-0 md:flex md:justify-end md:flex-row">
          <% unless user_signed_in? %>
          <%= link_to "Login/Cadastro", new_user_session_path, class: "px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
          <% end %>
          
          <% if user_signed_in? %>
          <!-- Settings Dropdown Here -->
            <%= button_to destroy_user_session_path, method: :delete, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
              SAIR
            <% end %>
          <% end %>
      </nav>
    </div>
  </div>
</div>